export interface SyndicateCharacter {
  id: string;
  number: string;
  name: string;
  characterTitle: string;
  alias: string;
  rank: string;
  quote: string;
  extendedQuote: string;
  suitId: string;
  suitName: string;
  priceFormatted: string;
  ballisticRating: string;
  archetypeTraits: string[];
  personalitySummary: string;
  syndicateCode: string;
  colorHex: string;
  accentColor: string;
  image: string;
  stampText: string;
}

export const SYNDICATE_CHARACTERS: SyndicateCharacter[] = [
  {
    id: "the-don",
    number: "01",
    name: "The Don",
    characterTitle: "THE DON",
    alias: "Il Capo dei Capi",
    rank: "Boss of Bosses",
    quote: "You don't ask for respect.",
    extendedQuote: "Uncompromising authority in Italian charcoal chalk-stripe and onyx wool. When you step into a room wearing The Don, nobody asks questions.",
    suitId: "the-don",
    suitName: "The Don — Classic Onyx & Chalk-Stripe",
    priceFormatted: "₹ 3,45,000",
    ballisticRating: "Level III-A Ballistic",
    archetypeTraits: ["Absolute Authority", "Cigar & Fedora", "Handcrafted Double-Breasted Cut"],
    personalitySummary: "The supreme patriarch of the Five Families. Never raises his voice; the entire room quiets down to hear him breathe.",
    syndicateCode: "RULE #1 • NEVER RAISE YOUR VOICE",
    colorHex: "#8B0000",
    accentColor: "#D4AF37",
    image: "/images/characters/the-don.jpg",
    stampText: "CLASS 1 • BOSS APPROVED",
  },
  {
    id: "the-boss",
    number: "02",
    name: "The Boss",
    characterTitle: "THE BOSS",
    alias: "The Executive Kingpin",
    rank: "Syndicate Head",
    quote: "You already have it.",
    extendedQuote: "Sovereign power in midnight navy 3-piece bespoke. Commands whole empires and corporate holding syndicates behind closed mahogany doors.",
    suitId: "the-boss",
    suitName: "The Boss — Midnight Navy 3-Piece",
    priceFormatted: "₹ 3,10,000",
    ballisticRating: "Level II-A Executive Core",
    archetypeTraits: ["Corporate Titan", "Vintage Watch Chain", "Penthouse Sovereign"],
    personalitySummary: "The strategic mind who monetizes the underworld into legitimate skyscraper boardrooms. A single signature shifts millions.",
    syndicateCode: "RULE #2 • OWN THE CONTRACT, OWN THE TOWN",
    colorHex: "#0F172A",
    accentColor: "#38BDF8",
    image: "/images/characters/the-boss.jpg",
    stampText: "EXECUTIVE CLEARANCE",
  },
  {
    id: "the-capo",
    number: "03",
    name: "The Capo",
    characterTitle: "THE CAPO",
    alias: "The District Commander",
    rank: "Caporegime",
    quote: "Quiet moves. Serious results.",
    extendedQuote: "Steely resolve in indestructible Como charcoal houndstooth and heavy worsted wool. Commands five city boroughs with unflinching discipline.",
    suitId: "the-capo",
    suitName: "The Capo — Heavy Como Charcoal Houndstooth",
    priceFormatted: "₹ 2,95,000",
    ballisticRating: "Level III Tactical",
    archetypeTraits: ["Territory Commander", "Reinforced Seams", "Tactical Houndstooth"],
    personalitySummary: "The street general who gets things done on schedule, every time, no excuses. Loyal to the Don, merciless to rivals.",
    syndicateCode: "RULE #3 • PROMISES DELIVERED IN CASH & IRON",
    colorHex: "#1E1E1C",
    accentColor: "#E9DFC9",
    image: "/images/characters/the-capo.jpg",
    stampText: "DISTRICT SECURED",
  },
  {
    id: "the-consigliere",
    number: "04",
    name: "The Consigliere",
    characterTitle: "THE CONSIGLIERE",
    alias: "The Mastermind",
    rank: "Legal Architect",
    quote: "Every detail has a purpose.",
    extendedQuote: "Effortless intellect in hand-rolled Sicilian cream linen with chalk stripes. Resolves multi-million dollar sit-downs with a calm smile before anyone draws a piece.",
    suitId: "the-consigliere",
    suitName: "The Consigliere — Sicilian Cream Chalk-Stripe Linen",
    priceFormatted: "₹ 2,80,000",
    ballisticRating: "Level II-A Micro-Mesh",
    archetypeTraits: ["Intellectual Shadow", "Gold Spectacles", "Breathable Linen Core"],
    personalitySummary: "The consigliere who navigates city ordinances, courtrooms, and treaty conferences. The brain behind the family's longevity.",
    syndicateCode: "RULE #4 • A SHARP TONGUE SILENCES TEN BULLETS",
    colorHex: "#2A251D",
    accentColor: "#B59454",
    image: "/images/characters/the-consigliere.jpg",
    stampText: "CONFIDENTIAL ADVISOR",
  },
  {
    id: "the-enforcer",
    number: "05",
    name: "The Enforcer",
    characterTitle: "THE ENFORCER",
    alias: "The Iron Fist",
    rank: "Prime Enforcer",
    quote: "No hesitation.",
    extendedQuote: "Intimidating imperial burgundy French velvet with razor satin peak lapels. When diplomatic negotiations fail, conversation is officially over.",
    suitId: "the-enforcer",
    suitName: "The Enforcer — Royale Burgundy Velvet",
    priceFormatted: "₹ 2,65,000",
    ballisticRating: "Level III Tactical Composite",
    archetypeTraits: ["Kinetic Dominance", "Burgundy Velvet", "Brass Skull Anchors"],
    personalitySummary: "The unstoppable immovable force. When The Enforcer steps across the door, contracts get settled instantly without negotiation.",
    syndicateCode: "RULE #5 • ACT WITHOUT DOUBT OR DELAY",
    colorHex: "#4C0519",
    accentColor: "#B92720",
    image: "/images/characters/the-enforcer.jpg",
    stampText: "LETHAL ENFORCEMENT",
  },
  {
    id: "the-underboss",
    number: "06",
    name: "The Underboss",
    characterTitle: "THE UNDERBOSS",
    alias: "The Shadow General",
    rank: "Underboss",
    quote: "Power doesn't need volume.",
    extendedQuote: "Tactical covert olive wool with stealth matte brass hardware and acoustic silent lining. You won't hear him coming, and you won't see him leave.",
    suitId: "the-underboss",
    suitName: "The Underboss — Covert Olive Cavalry Twill",
    priceFormatted: "₹ 2,50,000",
    ballisticRating: "Level IV Stealth Composite",
    archetypeTraits: ["Silent Tactician", "Acoustic Lining", "Covert Cavalry Twill"],
    personalitySummary: "The field director who manages day-to-day operations with military precision. Keeps the family machinery operating like clockwork.",
    syndicateCode: "RULE #6 • THE SHADOW STRIKES BEFORE THE LIGHT",
    colorHex: "#141A12",
    accentColor: "#84CC16",
    image: "/images/characters/the-underboss.jpg",
    stampText: "COVERT SILHOUETTE",
  },
  {
    id: "the-wildcard",
    number: "07",
    name: "The Wildcard",
    characterTitle: "THE WILDCARD",
    alias: "The Casino Maverick",
    rank: "High Roller",
    quote: "Rules were made to be rewritten.",
    extendedQuote: "High-voltage royal cobalt blue wool with metallic silver pinstripes and solid brass dice buttons. Bold, magnetic, and completely fearless at high-stakes tables.",
    suitId: "the-wildcard",
    suitName: "The Wildcard — Royal Cobalt Silver Pinstripe",
    priceFormatted: "₹ 2,75,000",
    ballisticRating: "Level II-A High-Flex",
    archetypeTraits: ["Casino Maverick", "Dice Cuff Buttons", "High-Voltage Cobalt"],
    personalitySummary: "The high-roller rogue who turns impossible odds into windfall victories. Flamboyant, unpredictable, and always two moves ahead of the house.",
    syndicateCode: "RULE #7 • ALWAYS DOUBLE DOWN ON RED",
    colorHex: "#172554",
    accentColor: "#38BDF8",
    image: "/images/characters/the-wildcard.jpg",
    stampText: "CASINO ROYALE",
  },
];
